const data = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    discountPercentage: 12.96,
    brand: "Apple",
    category: "smartphones",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 899,
    discountPercentage: 17.94,
    brand: "Apple",
    category: "smartphones",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    discountPercentage: 15.46,
    brand: "Samsung",
    category: "smartphones",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    discountPercentage: 17.91,
    brand: "OPPO",
    category: "smartphones",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    discountPercentage: 10.58,
    brand: "Huawei",
    category: "smartphones",
  },
  {
    id: 6,
    title: "MacBook Pro",
    price: 1749,
    discountPercentage: 11.02,
    brand: "Apple",
    category: "laptops",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    price: 1499,
    discountPercentage: 4.15,
    brand: "Samsung",
    category: "laptops",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    price: 1499,
    discountPercentage: 10.23,
    brand: "Microsoft Surface",
    category: "laptops",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    price: 1099,
    discountPercentage: 11.83,
    brand: "Infinix",
    category: "laptops",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    price: 1099,
    discountPercentage: 6.18,
    brand: "HP Pavilion",
    category: "laptops",
  },
];
